Repository crypto-org-chain/chain-main, pull requests merged in 2025-08, with the labels that each got.

#1181 fix: makefile + add run local chain script
  CHANGELOG.md
  Makefile
  run-local-chain.sh
Labels: Type: Build

#1184 ci: add issue labeler config
  .github/issue_labeler.yml
  .github/pr_labeler.yml
  .github/workflows/build.yml
  .github/workflows/lint.yml
  .github/workflows/nix.yml
  .github/workflows/release.yml
  pystarport/default.nix
Labels: ci

#1193 chore: add docs for rocksdb compilation
  Makefile
  readme.md
Labels: build
